alias tsc='docker run --rm -it -v ${PWD}:${PWD} -w ${PWD} typescripttrainning_tsc3.9.7 tsc'
alias node='docker run --rm -it -v ${PWD}:${PWD} -w ${PWD} typescripttrainning_tsc3.9.7 node'
alias npm='docker run --rm -it -v ${PWD}:${PWD} -w ${PWD} typescripttrainning_tsc3.9.7 npm'
alias tsd='docker run --rm -it -v ${PWD}:${PWD} -w ${PWD} typescripttrainning_tsc3.9.7 tsd'
alias eslint='docker run --rm -it -v ${PWD}:${PWD} -w ${PWD} typescripttrainning_tsc3.9.7 eslint'
